<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.20">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.20" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DDD.Application\DDD.Application.csproj" />
    <ProjectReference Include="..\DDD.Domain\DDD.Domain.csproj" />
    <ProjectReference Include="..\DDD.Eventing.Contracts\DDD.Eventing.Contracts.csproj" />
    <ProjectReference Include="..\DDD.MessageBroker.Contracts\DDD.MessageBroker.Contracts.csproj" />
  </ItemGroup>

</Project>
